### ISSUE TITLE
Video-stacks feature broke root typecheck and a videos DB test on master

### ISSUE THREAD

**Issue by vtempest** [debate/debate-ai.com#825]
## Context

Found while validating #826 (`coachingSessions` account sync). Confirmed present on `master` (`09b3dea`) too, with no local changes — both breaks predate that PR and are unrelated to it. This is also currently blocking the repo's `auto-merge-claude.yml` workflow for every PR (it waits on the "Vitest + coverage" check, which fails on this).

## Break 1: `bun run typecheck` fails in `debate-videos` — a botched merge, not a typo

```
src/components/video-grid/VideoGrid.tsx(83,24): error TS2304: Cannot find name 'VideoCard'.
src/panels/LecturesVideoGridView.tsx(446,17): error TS2322: Type '{ ... stackLinkedRounds: boolean; }' is not assignable to type 'IntrinsicAttributes & VideoGridProps'.
  Property 'stacks' does not exist on type 'IntrinsicAttributes & VideoGridProps'.
```

**Root cause (confirmed via `git blame`/`git log -p`), more involved than it first looks:** two independent, competing "stack videos together" features were built in parallel and landed via a bad merge:

- `7d42de5` (vtempest, 2026-09-13 18:45 PDT, "Link round analyses with full debate videos") rewrote `VideoGrid.tsx` around a **client-derived** `stackLinkedRounds` prop: a local `VideoStack` component, `ROUND_ANALYSIS_LINKS`, and a `fetch` to pull in a missing linked round/analysis video, grouping pairs at render time. This is the version currently in the file's function body (`VideoGridComponent`, the local `VideoStack` component, `displayedVideos`).
- `1747c08` (a prior Claude session, 2026-09-14 05:14 UTC, "stacked playlists, single sidebar highlight, in-app /features") independently rewrote the **same component** around a **server-derived** `stacks`/`stacksEnabled` prop pair: `stack_key`/`stack_position` columns stamped by migration `0041_video_stacks.sql`, `buildVideoSlots`, and rendering through `StackedVideoCard` (which itself wraps the real `VideoCard` plus `StackNav`).
- Merge commit `8267338` ("Merge branch 'master' into claude/sweet-curie-uym5ue") combined the two: `git blame` shows the file's import line 16 (`import { StackedVideoCard } from "../video-card/StackedVideoCard"`) and the fileoverview comment came from `1747c08`, but the entire function body — the local `VideoStack` component, `stackLinkedRounds`, the bare `<VideoCard>` JSX reference, and the *absence* of `stacks`/`stacksEnabled` from `VideoGridProps` — came from `7d42de5`. Neither side's code survived intact: the import/interface reflect one feature, the component body reflects the other, and `LecturesVideoGridView.tsx` (which calls `<VideoGrid>`) still passes the `stacks` prop `1747c08`'s version expected.

**This needs a decision, not a mechanical patch:** picking either feature's implementation outright drops the other (server-derived stacking of round+analysis-video pairs via `stack_key`, vs. client-derived linking via `ROUND_ANALYSIS_LINKS`) unless someone reconciles them (e.g. `buildVideoSlots`/`stacks` could plausibly subsume `stackLinkedRounds`'s job, or the two could run side by side) — worth resolving with whoever owns `debate-videos`/the stacking feature rather than guessing which behavior to keep.

## Break 2: a videos DB test fails against a stale migration fixture

```
apps/debate-ai.com/lib/videos/__tests__/seed-videos-to-db.test.ts
LibsqlBatchError: SQLITE_ERROR: table videos has no column named stack_key
```

Root cause: `seed-videos-to-db.test.ts`'s `freshDb()` helper only applies `drizzle/0005_green_redwing.sql` (the `videos` table's original creation) to its in-memory database. `drizzle/0041_video_stacks.sql` later added `stack_key`/`stack_position` columns to `videos`, and `seedVideosIntoDb` now writes those columns — but the test fixture was never updated to also apply `0041_video_stacks.sql`, so every test in that file fails against the incomplete schema. This one **is** a mechanical fix: apply `0041_video_stacks.sql` (and audit for any other migration after `0005` touching `videos`) in `freshDb()`.

## Suggested scope

- Break 1: needs a product/architecture call on which stacking behavior (or a merged combination of both) `VideoGrid`/`VideoGridProps` should implement, then a clean single implementation — not a patch over the current hybrid.
- Break 2: update `freshDb()` in `seed-videos-to-db.test.ts` to also apply `0041_video_stacks.sql`.
- Worth checking why `.github/workflows/test.yml` didn't already catch this on `1747c08`'s or `7d42de5`'s own PR before merge.

## Non-goals

Not blocking #826, which touches `debate-data-sync`/`debate-practice-drills` only and is unrelated.

**Comment by vtempest** [comment]
Opened #830 for "Break 1" — the botched `VideoGrid.tsx` merge. Resolution: kept the server-derived `stacks`/`stacksEnabled` implementation (general, already tested) and retired the client-derived `stackLinkedRounds`/`ROUND_ANALYSIS_LINKS` feature, since its 3 hardcoded pairs are already auto-detected by the server's `stack_key` derivation (their descriptions carry the same "Full Round"/"Full Debate" links `buildVideoStacks` already parses) and `LecturesVideoGridView` already had a separate, proper "Stacked playlists" toggle doing the same job.

"Break 2" (the `seed-videos-to-db` test fixture) remains tracked by #829 — untouched here, per this issue's own scoping.

---
_Generated by [Claude Code](https://claude.ai/code/session_011UJcfuZWHE7qcQ4FLvr2FW)_

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by vtempest** [comment]
#830 merged and carried both fixes (Break 1's `VideoGrid` reconciliation, plus Break 2's `seed-videos-to-db` migration-fixture fix ported from #829). `master` (198ae23) now has `bun run typecheck`, `bun run test`, and `bun run build` all green. Closing.

#829 is now redundant — its change already landed via #830 — so it should close as superseded rather than be merged on top.

---
_Generated by [Claude Code](https://claude.ai/code/session_011UJcfuZWHE7qcQ4FLvr2FW)_

---
_Generated by [Claude Code](https://claude.ai/code)_
